### ISSUE TITLE
On startup strange board rendering

### ISSUE THREAD

**Issue by damonachey** [sladewasinger/tronbox#1]
![image](https://user-images.githubusercontent.com/1005594/157150715-ff27bc73-7370-465a-bc41-b6c157bcc62b.png)

Repro steps:

1) Start new chrome window
2) paste in url 'https://sladewasinger.github.io/tronbox/'
3) notice good render

4) hit CTRL-R
5) notice bad render

**Comment by sladewasinger** [comment]
I'm seeing this behavior as well, and it appears to be random. I am investigating...

**Comment by sladewasinger** [comment]
Fixed issue with latest push - it seems I misunderstood canvas sizing. The width and height attributes on the canvas itself are necessary, the css width and height are for scaling/skewing.
