### ISSUE TITLE
bounds checking occurs after reference

### ISSUE THREAD

**Issue by damonachey** [sladewasinger/tronbox#2]
pos values are checked after reference

https://github.com/sladewasinger/tronbox/blob/211fe1258fd68f7ac39a2b015f512557f91dc867/spa/src/components/tron-box/tron/models/GridExtensions.js#L10

reference here

https://github.com/sladewasinger/tronbox/blob/211fe1258fd68f7ac39a2b015f512557f91dc867/spa/src/components/tron-box/tron/models/GridExtensions.js#L9

**Comment by sladewasinger** [comment]
Issue resolved with latest push!
